version: "3.1"
services:
    mongodb:
        image: mongo
        volumes:
            - mongo-full-text-volume:/usr/share/elasticsearch/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: laravel
        ports:
            - "27015:27017"
        networks:
            - app-net
    elastic:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
        volumes:
            - elastic-full-text-volume:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
        networks:
            - app-net
    redis:
        image: "redis:5-alpine"
        networks:
            - app-net
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: fulltext
            POSTGRES_DB: fulltext
            POSTGRES_USER: fulltext
        volumes:
            - db-full-text-volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-net
    php:
        image: "carlosocarvalho/app-fulltext-laravel:1.0.2"
        working_dir: /application
        command: "php artisan migrate --force"
        volumes:
            - applicationVolume:/application
        configs:  
            - 
             source: appEnv
             target: /application/.env
            - 
             source: appPHPIni
             target: /etc/php/7.3/fpm/conf.d/99-overrides.ini 
            
        networks:
            - app-net
    queue:
        image: "carlosocarvalho/app-fulltext-laravel:1.0.2"
        volumes:
            - applicationVolume:/application
        configs:  
            - 
             source: appEnv
             target: /application/.env
            - 
             source: appPHPIni
             target: /etc/php/7.3/fpm/conf.d/99-overrides.ini 
        command: "php artisan horizon"
        networks:
            - app-net
    schedule:
        image: "carlosocarvalho/app-fulltext-laravel:1.0.2"
        volumes:
            - applicationVolume:/application
        configs:  
            - 
             source: appEnv
             target: /application/.env
            - 
             source: appPHPIni
             target: /etc/php/7.3/fpm/conf.d/99-overrides.ini 
        environment:
            - CONTAINER_ROLE=scheduler
        command: start
        networks:
            - app-net
    nginx:
        image: "nginx:alpine"
        working_dir: /application
        volumes:
            - applicationVolume:/application
        configs:  
            - 
             source: appNginxConfig
             target: /etc/nginx/conf.d/default.conf
        deploy:
            labels:
                traefik.docker.network: web
                traefik.enable: "true"
                traefik.frontend: fulltext
                traefik.frontend.rule: "Host: 165.227.90.191"
                traefik.port: "80"
        networks:
            - web
            - app-net
networks:
    app-net:
        driver: overlay
    web:
        external: true
        
volumes:
    elastic-full-text-volume:
        external: true
    mongo-full-text-volume:
        external: true
    db-full-text-volume:
        external: true
    applicationVolume:
        external: true
           
configs:
  appEnv:
    external: true
  appNginxConfig:
    external: true
  appPHPIni:
    external: true