version: '3.1'

services:

  mongo:
    image: mongo
    volumes:
      - mongoVolume:/usr/share/elasticsearch/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: laravel
    ports: 
      - 27017:27017
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
volumes:
  esdata01:  
    driver: local
  mongoVolume:
    driver: local